version: '3.4'

volumes:
  mongodb:
  mongodb_config:
    driver: local

services:
    warehouse-ui:
        build: ./src/warehouse-ui
        tty: true
        ports:
            - "3001:80"
        volumes:
            - './src/warehouse-ui:/warehouse-service'

    warehouse:
        build: ./src/warehouse
        depends_on:
            - mongodb
        tty: true
        ports:
            - "3000:80"
        volumes:
            - './src/warehouse:/python-service'

    mongodb:
        image: mongodb
        build:
            context: ./src/mongodb
            dockerfile: Dockerfile
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
        - "27017:27017"
